### ISSUE TITLE
Добавить описание в ReadMe

### ISSUE THREAD

**Issue by Shiplayer** [codex-team/hawk.android#11]
- [x] Необходимо добавить описание проекта
- [x] Какие зависимости используются в проекте
- [x] Что необходимо скачать для полноценной разработки
- [x] Как запустить приложение
- [x] Инструкцию по тестированию

**Comment by Shiplayer** [comment]
@neSpecc Устраивают пункты для описания ReadMe или стоит еще что-то добавить?

**Comment by neSpecc** [comment]
> @neSpecc Устраивают пункты для описания ReadMe или стоит еще что-то добавить?

добавьте инструкцию по тестированию
