### ISSUE TITLE
Настройка lint для проекта

### ISSUE THREAD

**Issue by Shiplayer** [codex-team/hawk.android#2]
Настройти линт в соответствии со статьей https://developer.android.com/studio/write/lint

**Comment by Shiplayer** [comment]
Можно попробовать взять [ktlint](https://ktlint.github.io/) для проекта

**Comment by Shiplayer** [comment]
Добавляем ktlint, проверить, умеет ли он проверять код на документацию, если не умеет, то надо будет притянуть [dokka](https://github.com/Kotlin/dokka)

**Comment by Shiplayer** [comment]
Было бы неплохо в будущем написать какие-нибудь свои проверки для линта
https://www.youtube.com/watch?v=-4849t5fzJI

**Comment by Shiplayer** [comment]
Решил пока не добавлять dokka, так как она еще и генерирует саму документацию, пока не хотелось бы, как просто проверить, задокументирован ли код или нет, не понятно

**Comment by temnik15** [comment]
На будущее можно некоторые фишки подсмотреть https://www.youtube.com/watch?v=ElbrJyyE404&t=4s. Мне в частности понравилась возможность предоставлять шаблон для pr.
