### ISSUE TITLE
Сделать бейдж для отображения количества

### ISSUE THREAD

**Issue by Shiplayer** [codex-team/hawk.android#39]
- [ ] Унаследовать от FrameLayout
- [ ] Обновлять данные с помощью BadgeViewModel
- [ ] Логику обработки количества и предоставления готового текста, сделать отдельным классом

**Comment by temnik15** [comment]
@Shiplayer по поводу 3 пункта, разве не решили упаковать логику обработки внутрь бэйджа?

**Comment by Shiplayer** [comment]
можно будет посмотреть, как реализована тут тень для вьюшки https://gist.github.com/nickbutcher/1dcde5a989011d01fda491bc9a59c21e
